### ISSUE TITLE
datop doesn't work on a non-numa arm64 machine

### ISSUE THREAD

**Issue by BarrySong666** [aliyun/data-profile-tools#4]
details can be found here:
https://lore.kernel.org/lkml/CAGsJ_4wK=Xw7g=FZgRBo4FRK11AeyS0Jyrd7D0UeDe3DLVUmfA@mail.gmail.com/

~/data-profile-tools # pgrep youtube
12700
~/data-profile-tools # ./datop -p 12700 -l 2 -f error.log
Start monitoring 12700 ...
DamonTOP is starting ...
DamonTop is exiting ...
~/data-profile-tools # cat error.log 
0: calibrate_cpufreq: nsofclk = 0.5541, clkofsec = 1804800000
0: Detected 8 online CPUs
0: TODO: stop perf
0: pf_profiling_setup: attr.type = 0x2, attr.config = 0xf8
0: begin to monitor: 14669
0: os_profiling_start success
27: disp thread received CMD_QUIT_ID
27: Send PERF_QUIT_ID to perf thread
27: perf_handler: received QUIT
27: TODO: stop perf
27: perf thread is exiting.
27: perf thread exit yet
27: disp thread is exiting
27: disp thread exit yet
27: Send PIPE_CHAR_QUIT to cons thread
27: cons: received PIPE_CHAR_QUIT
27: cons thread is exiting
27: cons thread exit yet

**Comment by wangrongwei** [comment]
It's so strange. I don't find any error messages.

Let me think...

**Comment by wangrongwei** [comment]
datop:

~/data-profile-tools # ./datop -p 21287

Monitoring 1 processes (interval: 5.1s)

   PID           PROC       TYPE           START             END     SIZE(KiB)   *ACCESS      AGE
 21287    android.you       ----               0               0          0         0        0

Did you have clicked 'enter' for the first row? The moniproc window will displays and shows detailed regions for this process when clicking 'enter'.
